-- =========================================================
-- 024_translation_reviews.sql
-- Persistent translation review/workflow state
-- =========================================================
--
-- Purpose:
--   Persist manual and review-based translation state so the
--   workflow survives process restarts, redeploys and multiple
--   webhook workers.
--
-- This table stores workflow state only.
-- It does NOT publish content and does NOT replace the shared
-- publication engine.
--
-- =========================================================


CREATE TABLE IF NOT EXISTS public.translation_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id TEXT NOT NULL UNIQUE,

    user_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,

    source_language TEXT NOT NULL DEFAULT 'auto',
    target_language TEXT,

    original_text TEXT NOT NULL DEFAULT '',
    translated_text TEXT,
    edited_text TEXT,

    status TEXT NOT NULL DEFAULT 'waiting_language',

    content_kind TEXT NOT NULL DEFAULT 'text',

    source_review_id TEXT,
    source_message_id BIGINT,

    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    validation_warnings JSONB NOT NULL DEFAULT '[]'::jsonb,

    translation_attempts INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (
        NOW() + INTERVAL '24 hours'
    ),

    CONSTRAINT translation_reviews_status_check
        CHECK (
            status IN (
                'waiting_language',
                'waiting_custom_language',
                'translating',
                'preview',
                'waiting_edit',
                'confirmed',
                'cancelled',
                'failed'
            )
        ),

    CONSTRAINT translation_reviews_attempts_check
        CHECK (translation_attempts >= 0)
);


-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS
    idx_translation_reviews_user_chat
ON public.translation_reviews (
    user_id,
    chat_id
);


CREATE INDEX IF NOT EXISTS
    idx_translation_reviews_status
ON public.translation_reviews (
    status
);


CREATE INDEX IF NOT EXISTS
    idx_translation_reviews_expires_at
ON public.translation_reviews (
    expires_at
);


CREATE INDEX IF NOT EXISTS
    idx_translation_reviews_source_review_id
ON public.translation_reviews (
    source_review_id
)
WHERE source_review_id IS NOT NULL;


-- Only one active translation workflow should normally exist
-- for a user/chat pair.
--
-- Terminal reviews do not block creation of a new workflow.
CREATE UNIQUE INDEX IF NOT EXISTS
    uq_translation_reviews_active_user_chat
ON public.translation_reviews (
    user_id,
    chat_id
)
WHERE status IN (
    'waiting_language',
    'waiting_custom_language',
    'translating',
    'preview',
    'waiting_edit'
);


-- =========================================================
-- UPDATED_AT TRIGGER
-- =========================================================

CREATE OR REPLACE FUNCTION
    public.set_translation_reviews_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


DROP TRIGGER IF EXISTS
    trg_translation_reviews_updated_at
ON public.translation_reviews;


CREATE TRIGGER
    trg_translation_reviews_updated_at
BEFORE UPDATE
ON public.translation_reviews
FOR EACH ROW
EXECUTE FUNCTION
    public.set_translation_reviews_updated_at();


-- =========================================================
-- EXPIRED REVIEW CLEANUP HELPER
-- =========================================================

CREATE OR REPLACE FUNCTION
    public.cleanup_expired_translation_reviews()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count INTEGER;
BEGIN

    DELETE FROM public.translation_reviews
    WHERE expires_at <= NOW();

    GET DIAGNOSTICS
        deleted_count = ROW_COUNT;

    RETURN deleted_count;

END;
$$;


-- =========================================================
-- COMMENTS
-- =========================================================

COMMENT ON TABLE public.translation_reviews IS
'Persistent state for multilingual translation review workflows.';


COMMENT ON COLUMN public.translation_reviews.review_id IS
'Stable application-level identifier for the translation workflow.';


COMMENT ON COLUMN public.translation_reviews.source_language IS
'Detected or explicitly supplied source language code; auto means unresolved.';


COMMENT ON COLUMN public.translation_reviews.target_language IS
'Requested destination language code or normalized language value.';


COMMENT ON COLUMN public.translation_reviews.original_text IS
'Original untranslated content.';


COMMENT ON COLUMN public.translation_reviews.translated_text IS
'Machine translated preview before optional manual editing.';


COMMENT ON COLUMN public.translation_reviews.edited_text IS
'Optional user-edited translation used after review.';


COMMENT ON COLUMN public.translation_reviews.source_review_id IS
'Optional identifier of the originating editorial or external review workflow.';


COMMENT ON COLUMN public.translation_reviews.metadata IS
'Extensible workflow metadata without coupling translation state to publication.';


COMMENT ON COLUMN public.translation_reviews.expires_at IS
'Expiration time for temporary translation workflow state.';


-- =========================================================
-- SECURITY
-- =========================================================
--
-- Application access is expected through the existing trusted
-- backend/service-role Supabase client.
--
-- Enabling RLS prevents accidental direct client access while
-- service-role access remains available.
-- =========================================================

ALTER TABLE public.translation_reviews
ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- MIGRATION COMPLETE
-- =========================================================
