-- =========================================================
-- 036_admin_control_layer.sql
-- Independent administrative control layer.
--
-- Goals:
--   * Do not alter existing publication/workspace behavior.
--   * Existing destinations remain allowed by default.
--   * Admin pause/block state is stored separately.
--   * Invite codes and add-destination approvals are isolated.
--   * All administrative actions can be audited.
-- =========================================================


-- =========================================================
-- DESTINATION ADMIN CONTROL
-- =========================================================

create table if not exists public.admin_destination_controls (
    id bigint generated by default as identity primary key,

    destination_id bigint not null
        references public.publication_destinations(id)
        on delete cascade,

    admin_state text not null default 'active'
        check (admin_state in ('active', 'paused', 'blocked')),

    reason text null,

    changed_by_platform text null
        check (
            changed_by_platform is null
            or changed_by_platform in ('telegram', 'bale', 'system')
        ),

    changed_by_external_user_id bigint null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    unique (destination_id)
);

create index if not exists
    admin_destination_controls_state_idx
on public.admin_destination_controls(admin_state);


-- =========================================================
-- ONE-TIME INVITE CODES
-- Store only a hash of the issued code.
-- =========================================================

create table if not exists public.admin_invite_codes (
    id bigint generated by default as identity primary key,

    code_hash text not null unique,

    purpose text not null default 'registration'
        check (purpose in ('registration', 'add_destination')),

    status text not null default 'active'
        check (status in ('active', 'used', 'revoked')),

    bound_platform text null
        check (
            bound_platform is null
            or bound_platform in ('telegram', 'bale')
        ),

    bound_external_user_id bigint null,

    expires_at timestamptz null,

    used_at timestamptz null,

    used_by_user_id bigint null
        references public.users(id)
        on delete set null,

    created_by_platform text null
        check (
            created_by_platform is null
            or created_by_platform in ('telegram', 'bale', 'system')
        ),

    created_by_external_user_id bigint null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists
    admin_invite_codes_status_idx
on public.admin_invite_codes(status);

create index if not exists
    admin_invite_codes_expires_at_idx
on public.admin_invite_codes(expires_at);


-- =========================================================
-- ADMIN APPROVAL REQUESTS
-- Initially used for Add Channel / Add Destination approval.
-- =========================================================

create table if not exists public.admin_access_requests (
    id bigint generated by default as identity primary key,

    request_type text not null
        check (request_type in ('add_destination')),

    requester_user_id bigint not null
        references public.users(id)
        on delete cascade,

    workspace_id bigint not null
        references public.workspaces(id)
        on delete cascade,

    platform text not null
        check (platform in ('telegram', 'bale')),

    external_id text not null,
    normalized_external_id text not null,

    display_name text null,

    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'rejected',
                'cancelled'
            )
        ),

    review_reason text null,

    reviewed_by_platform text null
        check (
            reviewed_by_platform is null
            or reviewed_by_platform in ('telegram', 'bale', 'system')
        ),

    reviewed_by_external_user_id bigint null,

    reviewed_at timestamptz null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists
    admin_access_requests_status_idx
on public.admin_access_requests(status);

create index if not exists
    admin_access_requests_requester_idx
on public.admin_access_requests(requester_user_id);

create index if not exists
    admin_access_requests_workspace_idx
on public.admin_access_requests(workspace_id);

create index if not exists
    admin_access_requests_destination_lookup_idx
on public.admin_access_requests(
    platform,
    normalized_external_id
);


-- Prevent duplicate simultaneous pending requests for the same
-- physical destination inside the same workspace.
create unique index if not exists
    admin_access_requests_one_pending_destination_idx
on public.admin_access_requests(
    requester_user_id,
    workspace_id,
    platform,
    normalized_external_id
)
where status = 'pending';


-- =========================================================
-- ADMIN AUDIT LOG
-- Append-only application log for administrative operations.
-- =========================================================

create table if not exists public.admin_audit_log (
    id bigint generated by default as identity primary key,

    action text not null,

    actor_platform text not null
        check (actor_platform in ('telegram', 'bale', 'system')),

    actor_external_user_id bigint null,

    target_type text not null
        check (
            target_type in (
                'destination',
                'invite_code',
                'access_request',
                'user',
                'workspace'
            )
        ),

    target_id bigint null,

    details jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now()
);

create index if not exists
    admin_audit_log_created_at_idx
on public.admin_audit_log(created_at desc);

create index if not exists
    admin_audit_log_target_idx
on public.admin_audit_log(target_type, target_id);


-- =========================================================
-- IMPORTANT COMPATIBILITY RULE
--
-- No publication_destination rows are backfilled here.
-- Absence of an admin_destination_controls row must be treated
-- by application code as allowed/active.
--
-- This preserves all existing users and destinations until the
-- Admin Control feature flag is enabled and an explicit admin
-- action changes a destination.
-- =========================================================