-- =========================================================
-- 037_user_registration_approval.sql
-- Admin approval foundation for new user registration.
--
-- Existing users remain unchanged.
-- New users may use status='pending' until admin review.
-- =========================================================

begin;


-- =========================================================
-- USERS
-- Allow a newly registered user to wait for admin approval.
-- =========================================================

alter table public.users
    drop constraint if exists users_status_check;

alter table public.users
    add constraint users_status_check
    check (
        status in (
            'active',
            'inactive',
            'pending'
        )
    );


-- =========================================================
-- ADMIN REGISTRATION REQUESTS
--
-- Separate from admin_access_requests because registration
-- happens before the user owns or creates a workspace.
-- =========================================================

create table if not exists public.admin_registration_requests (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references public.users(id)
        on delete cascade,

    requested_platform text not null
        check (
            requested_platform in (
                'telegram',
                'bale'
            )
        ),

    requested_external_user_id bigint not null,

    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'rejected'
            )
        ),

    review_reason text null,

    reviewed_by_platform text null
        check (
            reviewed_by_platform is null
            or reviewed_by_platform in (
                'telegram',
                'bale',
                'system'
            )
        ),

    reviewed_by_external_user_id bigint null,

    reviewed_at timestamptz null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint admin_registration_requests_user_unique
        unique (user_id)
);


create index if not exists
    admin_registration_requests_status_idx
on public.admin_registration_requests(status);


create index if not exists
    admin_registration_requests_platform_user_idx
on public.admin_registration_requests(
    requested_platform,
    requested_external_user_id
);


commit;